// Enlaces del menú expresados como datos para el buscador global.
// `external: true` abre en pestaña nueva; `action` ejecuta una acción especial.
export const NAV_LINKS = [
  // Accesos rápidos de gestión de usuarios
  {
    id: 'cambiar-contrasena',
    title: 'Cambiar o recuperar contraseña',
    description: 'Abre la web para recuperar o cambiar tu clave de acceso.',
    tags: [
      'contraseña',
      'contrasena',
      'clave',
      'password',
      'recuperar contraseña',
      'cambiar contraseña',
      'olvide mi contraseña',
      'olvide clave',
      'gestion usuarios',
      'acceso',
    ],
    url: 'https://api.verfrut.cl/RecoverPass',
    external: true,
    icon: 'fi fi-rr-key',
  },
  {
    id: 'desbloqueo-usuario',
    title: 'Desbloqueo de Usuario',
    description: 'Desbloquea tu cuenta cuando haya quedado bloqueada por intentos fallidos.',
    tags: [
      'desbloquear',
      'desbloqueo',
      'usuario bloqueado',
      'cuenta bloqueada',
      'bloqueo',
      'clave',
      'password',
      'gestion usuarios',
      'acceso',
    ],
    url: 'https://api.verfrut.cl/recoverpass/unlockuser',
    external: true,
    icon: 'fi fi-rr-unlock',
  },
  {
    id: 'inicio',
    title: 'Página de inicio',
    description: 'Vuelve al inicio del portal de Informática.',
    tags: ['inicio', 'home', 'principal', 'portal'],
    url: '/',
    icon: 'fi fi-rr-home',
  },

  // Sistemas
  {
    id: 'apps',
    title: 'Apps',
    description: 'Portal de aplicaciones de Unifrutti.',
    tags: ['aplicaciones', 'portal', 'sistemas'],
    url: 'https://api.verfrut.cl',
    external: true,
    icon: 'fi fi-rr-apps',
  },
  {
    id: 'ctacte-envases',
    title: 'Sistema Cuenta Corriente Envases',
    description: 'Gestión de cuenta corriente de envases.',
    tags: ['envases', 'cuenta corriente', 'operacional'],
    url: 'https://api.verfrut.cl/ctacteenvases',
    external: true,
    icon: 'fi fi-rr-truck-check',
  },
  {
    id: 'dte',
    title: 'Sistema Documentos Electrónicos (DTE)',
    description: 'Facturas, boletas y guías electrónicas ante el SII.',
    tags: ['dte', 'factura', 'boleta', 'sii', 'facturacion'],
    url: 'https://facturacion.verfrut.cl/Account/Login?ReturnUrl=%2f',
    external: true,
    icon: 'fi fi-rr-file',
  },
  {
    id: 'rendiciones',
    title: 'Sistema Rendiciones',
    description: 'Rendición de gastos y viáticos.',
    tags: ['rendiciones', 'gastos', 'viaticos', 'reembolso'],
    url: 'https://rendiciones.verfrut.cl',
    external: true,
    icon: 'fi fi-rr-usd-circle',
  },
  {
    id: 'vacaciones',
    title: 'Sistema Vacaciones y Permisos',
    description: 'Solicitud de vacaciones y permisos.',
    tags: ['vacaciones', 'permisos', 'feriado', 'rrhh'],
    url: 'https://api.verfrut.cl/vacaciones',
    external: true,
    icon: 'fi fi-rr-umbrella-beach',
  },

  // Soporte
  {
    id: 'reportar-incidencia',
    title: 'Reportar Incidencia',
    description: 'Abre el portal de incidencias de tu país (Chile o Perú).',
    tags: ['incidencia', 'reportar', 'soporte', 'problema', 'ticket'],
    action: 'report-incident',
    vpn: true,
    icon: 'fi fi-rr-bug',
  },
  {
    id: 'solicitudes',
    title: 'Portal de Solicitudes',
    description: 'Solicitudes al área de TI.',
    tags: ['solicitud', 'requerimiento', 'soporte'],
    url: 'https://solicitudes.verfrut.cl',
    external: true,
    vpn: true,
    icon: 'fi fi-rr-form',
  },
  {
    id: 'glpi-chile',
    title: 'Portal de GLPI (Chile)',
    description: 'Mesa de ayuda GLPI para Chile.',
    tags: ['glpi', 'ticket', 'incidencia', 'chile', 'mesa de ayuda'],
    url: 'https://glpi.verfrut.cl',
    external: true,
    vpn: true,
    icon: 'fi fi-rr-headset',
  },
  {
    id: 'glpi-peru',
    title: 'Portal de GLPI (Perú)',
    description: 'Mesa de ayuda GLPI para Perú.',
    tags: ['glpi', 'ticket', 'incidencia', 'peru', 'mesa de ayuda'],
    url: 'https://glpi.verfrut.pe',
    external: true,
    vpn: true,
    icon: 'fi fi-rr-headset',
  },
  {
    id: 'correo-soporte',
    title: 'Correo de Soporte',
    description: 'Escríbenos a soporte@verfrut.cl.',
    tags: ['correo', 'soporte', 'email', 'contacto'],
    url: 'mailto:soporte@verfrut.cl',
    external: true,
    icon: 'fi fi-rr-envelope',
  },

  // Seguridad
  {
    id: 'concientizacion',
    title: 'Concientización en Ciberseguridad',
    description: 'Portal SharePoint de concientización.',
    tags: ['ciberseguridad', 'seguridad', 'concientizacion', 'sharepoint'],
    url: 'https://verfrutsa.sharepoint.com/sites/Ciberseguridadconcientizacion',
    external: true,
    icon: 'fi fi-rr-shield-check',
  },
  {
    id: 'protocolos-seguridad',
    title: 'Protocolos de Seguridad',
    description: 'Buenas prácticas de seguridad de la información para colaboradores.',
    tags: ['protocolo', 'seguridad', 'ciberseguridad', 'contraseña', 'phishing', 'vpn'],
    url: '/blog/protocolos-seguridad',
    icon: 'fi fi-rr-document',
  },

  // Recursos y herramientas
  {
    id: 'manuales',
    title: 'Manuales',
    description: 'Carpeta de manuales de sistemas en SharePoint.',
    tags: ['manual', 'documentacion', 'material de apoyo'],
    url: 'https://verfrutsa-my.sharepoint.com/:f:/g/personal/jsazo_verfrut_cl/EoIKH1AvVABCvzypHMh2HxkBJFHPcLw6Pj_6LIY_TzsKYQ?e=1D6gra',
    external: true,
    icon: 'fi fi-rr-book-open-reader',
  },
  {
    id: 'base-conocimiento-erp',
    title: 'Base de conocimiento ERP',
    description: 'Procedimientos extraídos desde manuales internos para revisión progresiva.',
    tags: ['manuales erp', 'procedimientos', 'base conocimiento', 'manual', 'erp'],
    url: '/manuales',
    icon: 'fi fi-rr-book-open-cover',
  },
  {
    id: 'generar-firmas',
    title: 'Generar Firmas',
    description: 'Genera tu firma de correo corporativa.',
    tags: ['firma', 'correo', 'herramienta'],
    url: 'https://api.verfrut.cl/Home/GeneradorFirma',
    external: true,
    icon: 'fi fi-rr-file-signature',
  },
  {
    id: 'sugerencias',
    title: 'Sugerencias',
    description: 'Buzón de sugerencias para TI.',
    tags: ['sugerencia', 'feedback', 'buzon'],
    url: 'https://sugerencias.verfrut.cl/',
    external: true,
    icon: 'fi fi-rr-feedback',
  },

  // Páginas internas
  {
    id: 'anexos',
    title: 'Anexos Telefónicos',
    description: 'Directorio de anexos y correos del personal.',
    tags: ['anexo', 'telefono', 'directorio', 'correo', 'contacto'],
    url: '/anexos',
    icon: 'fi fi-rr-phone-call',
  },
  {
    id: 'turnos',
    title: 'Turnos',
    description: 'Responsables de soporte y desarrollo de la semana.',
    tags: ['turno', 'urgencia', 'soporte', 'telefono', 'semana'],
    url: '/turnos',
    icon: 'fi fi-rr-calendar-clock',
  },
  {
    id: 'blog',
    title: 'Blog',
    description: 'Artículos y noticias del equipo TI.',
    tags: ['blog', 'articulos', 'noticias'],
    url: '/blog',
    icon: 'fi fi-rr-newspaper',
  },
  {
    id: 'videos',
    title: 'Video Tutoriales',
    description: 'Videos de capacitación y tutoriales.',
    tags: ['video', 'tutorial', 'capacitacion'],
    url: '/videos',
    icon: 'fi fi-rr-video-camera-alt',
  },
  {
    id: 'guias',
    title: 'Guías paso a paso',
    description: 'Guías prácticas de TI explicadas paso a paso.',
    tags: ['guia', 'paso a paso', 'como hacer', 'tutorial'],
    url: '/guias',
    icon: 'fi fi-rr-book-open-cover',
  },
  {
    id: 'faq',
    title: 'Preguntas Frecuentes',
    description: 'Respuestas a las dudas más comunes de TI.',
    tags: ['faq', 'pregunta', 'duda', 'ayuda'],
    url: '/faq',
    icon: 'fi fi-rr-interrogation',
  },
  {
    id: 'glosario',
    title: 'Glosario TI',
    description: 'Términos de tecnología en lenguaje simple.',
    tags: ['glosario', 'termino', 'definicion', 'diccionario'],
    url: '/glosario',
    icon: 'fi fi-rr-book-alt',
  },
  {
    id: 'quiz-seguridad',
    title: 'Quiz de Ciberseguridad',
    description: 'Pon a prueba tus conocimientos de seguridad.',
    tags: ['quiz', 'test', 'ciberseguridad', 'phishing'],
    url: '/quiz-seguridad',
    icon: 'fi fi-rr-brain',
  },
]
